#!/bin/bash

if [ "$1" = "--quick" ]; then
	repo=rastapank/flow-dashboard:latest
	docker pull $repo
	containerName=flow-dashboard-upstream
else
	repo=rastapank/flow-dashboard:local-build
	containerName=flow-dashboard-local
fi

# Make a shared directory, which can be accessed by both host and container.
# It can be used for sharing schedule files.
sharedDirName=schedules
mkdir -p $sharedDirName

if [ -d "$sharedDirName" ]; then
	hostSharedDirPath=`pwd`/$sharedDirName
	containerSharedDirPath=/opt/flow-dashboard/$sharedDirName
	makeSharedDir="-v $hostSharedDirPath:$containerSharedDirPath"

else
	echo "[!] Shared directory \"$sharedDir\" not found. Manual copy of the schedule to/from container is required."
	makeSharedDir=""
fi

runCommand="docker run -t --rm -P $makeSharedDir --name $containerName $repo"
echo "[*] Executing: $runCommand"
$runCommand &
sleep 2

hostPort=`docker port flow-dashboard-local | cut -d ":" -f 2`
echo "[*] Listening on port: $hostPort"
