#!/bin/bash

if [ "$1" = "--quick" ]; then
	repo=rastapank/flow-dashboard:latest
	docker pull $repo
	containerName=flow-dashboard-upstream
else
	repo=rastapank/flow-dashboard:local-build
	containerName=flow-dashboard-local
fi

# Make a shared directory, which can be accessed by both host and container.
# It can be used for sharing schedule files.
sharedDirName=schedules
mkdir -p $sharedDirName

if [ -d "$sharedDirName" ]; then
	hostSharedDirPath=`pwd`/$sharedDirName
	containerSharedDirPath=/opt/flow-dashboard/$sharedDirName
	makeSharedDir="-v $hostSharedDirPath:$containerSharedDirPath"

else
	echo "[!] Shared directory \"$sharedDir\" not found. Manual copy of the schedule to/from container is required."
	makeSharedDir=""
fi

runCommand="docker run -t --rm -P $makeSharedDir --name $containerName $repo"
echo "[*] Executing: $runCommand"
$runCommand &
sleep 2

hostPort=`docker port $containerName | cut -d ":" -f 2`

if [ -n "$hostPort" ]; then
	URL="http://localhost:$hostPort"
	echo "[*] App is running on: $URL"

	if [ -n "$BROWSER" ]; then
		$BROWSER $URL
	elif which xdg-open > /dev/null; then
		xdg-open $URL
	elif which gnome-open > /dev/null; then
		gnome-open $URL
	elif [ `uname -s` = "Darwin" ]; then
		open $URL
	else
		echo "Could not detect the web browser to use. Please visit: $URL"
	fi
fi
